import type { NextPage } from "next";
import Head from "next/head";
import axios from "axios";
import Todo from "../components/Todo";

export const getStaticProps = async () => {
  const res = await axios.get('url');
  return {
    props: {
      data: res.data
    }
  }
};

const Home: NextPage = ({data}) => {
  return (
    <div>
      <Head>
        <title>Practice Next Ts</title>
        <meta name="description" media="Generated by create next app" />
      </Head>
      data.map(i => (
         <Todo data={i} />
      ))
    </div>
  );
};

export default Home;
